# Files distributed to students (.ok & tests/ handled automatically)
su19/hw/hw08.d: $(MATERIALS_DST)/su19/hw/hw08/causes_of_death.csv
su19/hw/hw08.d: $(MATERIALS_DST)/su19/hw/hw08/HERS.csv
su19/hw/hw08.d: $(MATERIALS_DST)/su19/hw/hw08/HERS-table.png