# Files distributed to students (.ok & tests/ handled automatically)
su19/hw/hw03.d: $(MATERIALS_DST)/su19/hw/hw03/unemployment.csv
su19/hw/hw03.d: $(MATERIALS_DST)/su19/hw/hw03/nst-est2016-alldata.csv
su19/hw/hw03.d: $(MATERIALS_DST)/su19/hw/hw03/scatter.png
su19/hw/hw03.d: $(MATERIALS_DST)/su19/hw/hw03/var1.png
su19/hw/hw03.d: $(MATERIALS_DST)/su19/hw/hw03/var2.png
su19/hw/hw03.d: $(MATERIALS_DST)/su19/hw/hw03/boston.csv
su19/hw/hw03.d: $(MATERIALS_DST)/su19/hw/hw03/manila.csv