# Files distributed to students (.ok & tests/ handled automatically)
su19/lab/lab04.d: $(MATERIALS_DST)/su19/lab/lab04/raw_compensation.csv
su19/lab/lab04.d: $(MATERIALS_DST)/su19/lab/lab04/movies_by_year.csv
su19/lab/lab04.d: $(MATERIALS_DST)/su19/lab/lab04/apply.png