# Files distributed to students (.ok & tests/ handled automatically)
su19/project/project2.d: $(MATERIALS_DST)/su19/project/project2/movies.csv
su19/project/project2.d: $(MATERIALS_DST)/su19/project/project2/proj3_test_set.csv
su19/project/project2.d: $(MATERIALS_DST)/su19/project/project2/stem.csv
su19/project/project2.d: $(MATERIALS_DST)/su19/project/project2/word_plot.png