# Files distributed to students (.ok & tests/ handled automatically)
su19/lab/lab05.d: $(MATERIALS_DST)/su19/lab/lab05/Austen_PrideAndPrejudice.txt
su19/lab/lab05.d: $(MATERIALS_DST)/su19/lab/lab05/player_data.csv
su19/lab/lab05.d: $(MATERIALS_DST)/su19/lab/lab05/salary_data.csv
su19/lab/lab05.d: $(MATERIALS_DST)/su19/lab/lab05/small_srswor_salary.csv
su19/lab/lab05.d: $(MATERIALS_DST)/su19/lab/lab05/large_srswor_salary.csv
su19/lab/lab05.d: $(MATERIALS_DST)/su19/lab/lab05/comparisons.png