# Files distributed to students (.ok & tests/ handled automatically)
su19/lab/lab02.d: $(MATERIALS_DST)/su19/lab/lab02/world_population.csv
su19/lab/lab02.d: $(MATERIALS_DST)/su19/lab/lab02/imdb.csv
su19/lab/lab02.d: $(MATERIALS_DST)/su19/lab/lab02/farmers_markets.csv
su19/lab/lab02.d: $(MATERIALS_DST)/su19/lab/lab02/statement.png