# Files distributed to students (.ok & tests/ handled automatically)
su19/lab/lab03.d: $(MATERIALS_DST)/su19/lab/lab03/world_population.csv
su19/lab/lab03.d: $(MATERIALS_DST)/su19/lab/lab03/array_logarithm.jpg
su19/lab/lab03.d: $(MATERIALS_DST)/su19/lab/lab03/array_multiplication.jpg
su19/lab/lab03.d: $(MATERIALS_DST)/su19/lab/lab03/more_restaurant_bills.csv
su19/lab/lab03.d: $(MATERIALS_DST)/su19/lab/lab03/excel_array.jpg
su19/lab/lab03.d: $(MATERIALS_DST)/su19/lab/lab03/chaining_method_calls.png
su19/lab/lab03.d: $(MATERIALS_DST)/su19/lab/lab03/imdb.csv