# Files distributed to students (.ok & tests/ handled automatically)
su19/hw/hw10.d: $(MATERIALS_DST)/su19/hw/hw10/restaurant_inspection_scores.csv
su19/hw/hw10.d: $(MATERIALS_DST)/su19/hw/hw10/united_summer2015.csv