# Files distributed to students (.ok & tests/ handled automatically)
su19/hw/hw11.d: $(MATERIALS_DST)/su19/hw/hw11/triple_vertical.csv
su19/hw/hw11.d: $(MATERIALS_DST)/su19/hw/hw11/btc.csv
su19/hw/hw11.d: $(MATERIALS_DST)/su19/hw/hw11/eth.csv
su19/hw/hw11.d: $(MATERIALS_DST)/su19/hw/hw11/spreads.csv