# Files distributed to students (.ok & tests/ handled automatically)
su19/hw/hw06.d: $(MATERIALS_DST)/su19/hw/hw06/player_data.csv
su19/hw/hw06.d: $(MATERIALS_DST)/su19/hw/hw06/salary_data.csv
su19/hw/hw06.d: $(MATERIALS_DST)/su19/hw/hw06/sample_salary_data.csv
su19/hw/hw06.d: $(MATERIALS_DST)/su19/hw/hw06/earthquakes_2017.csv