# Files distributed to students (.ok & tests/ handled automatically)
su19/lab/lab11.d: $(MATERIALS_DST)/su19/lab/lab11/close_novas.csv
su19/lab/lab11.d: $(MATERIALS_DST)/su19/lab/lab11/supernova.jpg
su19/lab/lab11.d: $(MATERIALS_DST)/su19/lab/lab11/drivers.csv