# Files distributed to students (.ok & tests/ handled automatically)
su19/hw/hw04.d: $(MATERIALS_DST)/su19/hw/hw04/causes_of_death.csv.zip
su19/hw/hw04.d: $(MATERIALS_DST)/su19/hw/hw04/abbreviations.csv
su19/hw/hw04.d: $(MATERIALS_DST)/su19/hw/hw04/faculty.csv
su19/hw/hw04.d: $(MATERIALS_DST)/su19/hw/hw04/berkeley_faculty.csv