# Files distributed to students (.ok & tests/ handled automatically)
su19/hw/hw02.d: $(MATERIALS_DST)/su19/hw/hw02/president_births.csv
su19/hw/hw02.d: $(MATERIALS_DST)/su19/hw/hw02/temperatures.csv
su19/hw/hw02.d: $(MATERIALS_DST)/su19/hw/hw02/world_population.csv
su19/hw/hw02.d: $(MATERIALS_DST)/su19/hw/hw02/array_diff.png
su19/hw/hw02.d: $(MATERIALS_DST)/su19/hw/hw02/array_cumsum.png
su19/hw/hw02.d: $(MATERIALS_DST)/su19/hw/hw02/old_faithful.csv
su19/hw/hw02.d: $(MATERIALS_DST)/su19/hw/hw02/inventory.csv
su19/hw/hw02.d: $(MATERIALS_DST)/su19/hw/hw02/sales.csv